knp_paginator:
    page_range: 5                      # Nombre de pages affichées dans la barre de pagination
    default_options:
        page_name: page                # Nom du paramètre GET pour la page (ex: ?page=2)
        sort_field_name: sort          # Nom du paramètre GET pour le tri
        sort_direction_name: order     # Nom du paramètre GET pour la direction du tri
        distinct: true                 # Éviter les doublons dans les résultats
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig' # Template Bootstrap 5