controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_default_route:
    path: /
    controller: App\Controller\FrontOfficeController::index